import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/modules/common/components/providers/providers';
import Script from 'next/script';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isDev = process.env.NODE_ENV === 'development';
  return (
    <html lang='hu'>
      <head>{isDev && <Script src='http://localhost:8097'></Script>}</head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
